#--------------------------------------------------
# Build worker image (VM template)
#--------------------------------------------------
image: Visual Studio 2017

#--------------------------------------------------
# Environment
#--------------------------------------------------
environment:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    secure: PNVFwcCuNr+X7SffsiwiVsa/JzVyZqwNJUbeve+Or/EjOwZxbd1CUC0K/5az9jsT    
  GIT_CONFIG_USER_EMAIL:
    secure: yAZjzbVhtfeKof5pGJ/N65IjSffBIJoX5MZIpqbtHkc=

#--------------------------------------------------
# Branch whitelist
#--------------------------------------------------
branches:
  # Whitelist
  only:
    - master

# Do not build on tags, since we auto-commit tags.
skip_tags: true

#--------------------------------------------------
# After cloning repository
#--------------------------------------------------
install:
  - git submodule init
  - git submodule update

#--------------------------------------------------
# Build configuration
#--------------------------------------------------
configuration: Release

#--------------------------------------------------
# Build hooks - before
#--------------------------------------------------
before_build:
# Patch version in csproj
  - ps: $temp_path = (Get-Item src\$env:APPVEYOR_PROJECT_NAME\$env:APPVEYOR_PROJECT_NAME.csproj).FullName
  - ps: $temp_csproj = [xml](Get-Content $temp_path)
  - ps: $temp_csproj.Project.PropertyGroup.Version = $temp_csproj.Project.PropertyGroup.Version -replace '\.[0-9]+$', ".$env:APPVEYOR_BUILD_NUMBER"
  - ps: $temp_csproj.Save($temp_path)
  - ps: $env:APPVEYOR_BUILD_VERSION = $temp_csproj.Project.PropertyGroup.Version
  - ps: Write-Host "Build version set to - $env:APPVEYOR_BUILD_VERSION"
# Restore
  - dotnet restore
    
#--------------------------------------------------
# Testing
# TODO: Figure out how to work with just the assembly output.
#--------------------------------------------------
test_script:
   - dotnet test test\%APPVEYOR_PROJECT_NAME%.Tests\%APPVEYOR_PROJECT_NAME%.Tests.csproj

#--------------------------------------------------
# Build hooks - after
#--------------------------------------------------
after_build:
# NOTE: "dotnet pack" is not supported yet, as per
# https://github.com/NuGet/Home/issues/4491
   - msbuild /t:pack src\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.csproj
 
#--------------------------------------------------
# Build hooks - on_success
#
# Tags the repository in GitHub with the release version.
#--------------------------------------------------
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_PERSONAL_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_CONFIG_USER_EMAIL%"
  - git config --global user.name "One Frame Link"
  - git tag "v%APPVEYOR_BUILD_VERSION%"
  - git push origin "v%APPVEYOR_BUILD_VERSION%"
 
#--------------------------------------------------
# NuGet config
#--------------------------------------------------
nuget:
  # disable publishing of .nupkg artifacts to
  # account/project feeds for pull request builds
  disable_publish_on_pr: true
  
#--------------------------------------------------
# Artifact configuration
#--------------------------------------------------
artifacts:  
  - path: '**\$(APPVEYOR_PROJECT_NAME).$(APPVEYOR_BUILD_VERSION).nupkg'
    name: NuGet

#--------------------------------------------------
# Deploy NuGet
#--------------------------------------------------
deploy:
  provider: NuGet
  api_key:
    secure: AhNvfOiNoCPXb1PnRG18sOfxSmsS+q4iNJ30PsuABsau99QGZ46C4nhSRSoUZehg
  artifact: NuGet
  
#--------------------------------------------------
# Notifications
#--------------------------------------------------
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Y4pw1Q3aqUk/4aVYHN5R3u5Zca5ijyVi6tRAVahXhlFXFCZTwpJLrEwHsRGoqQGIkUUpAOvlOpVRNoXBKJhfwkHybRotzfi7SbbB8Rb+67I= 
